// <auto-generated />
namespace CodeFrist.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class coursestudentrealtionships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coursestudentrealtionships));
        
        string IMigrationMetadata.Id
        {
            get { return "202204050758164_course student realtionships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
