// <auto-generated />
namespace CodeFrist.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initdbanddeptstudenttbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initdbanddeptstudenttbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202204050749337_init db and dept student tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
